#!/usr/bin/env node
// Build the @zero-arena/contracts npm package from the Foundry build
// artifacts. Reads ABIs out of `out/` and merges with
// `deployments/galileo-testnet.json` to produce a tiny dist/ tarball.
//
// Output:
//   dist/abi/AgentCertificate.json
//   dist/abi/ZeroArenaINFT.json
//   dist/abi/ReencryptionOracle.json
//   dist/addresses.json
//   dist/index.js
//   dist/index.d.ts

import { readFile, mkdir, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const CONTRACTS = ['AgentCertificate', 'ZeroArenaINFT', 'ReencryptionOracle'];

async function main() {
  const distDir = join(root, 'dist');
  if (existsSync(distDir)) await rm(distDir, { recursive: true, force: true });
  await mkdir(join(distDir, 'abi'), { recursive: true });

  // ─── 1. ABIs from out/<Name>.sol/<Name>.json ────────────────────────────
  const abiMap = {};
  for (const name of CONTRACTS) {
    const sourcePath = join(root, 'out', `${name}.sol`, `${name}.json`);
    if (!existsSync(sourcePath)) {
      throw new Error(
        `build-abi: ${sourcePath} not found. Run \`forge build\` first.`,
      );
    }
    const raw = JSON.parse(await readFile(sourcePath, 'utf8'));
    if (!Array.isArray(raw.abi)) throw new Error(`build-abi: malformed artifact at ${sourcePath}`);
    abiMap[name] = raw.abi;
    await writeFile(
      join(distDir, 'abi', `${name}.json`),
      JSON.stringify(raw.abi, null, 2),
    );
  }

  // ─── 2. deployment addresses ────────────────────────────────────────────
  const deployments = {};
  const deployPath = join(root, 'deployments', 'galileo-testnet.json');
  if (existsSync(deployPath)) {
    const raw = JSON.parse(await readFile(deployPath, 'utf8'));
    deployments.galileo = {
      chainId: raw.chainId,
      deployBlock: raw.deployBlock,
      addresses: raw.addresses,
    };
  } else {
    deployments.galileo = {
      chainId: 16602,
      deployBlock: null,
      addresses: {
        AgentCertificate: '0x0000000000000000000000000000000000000000',
        ZeroArenaINFT: '0x0000000000000000000000000000000000000000',
        ReencryptionOracle: '0x0000000000000000000000000000000000000000',
      },
    };
  }
  await writeFile(join(distDir, 'addresses.json'), JSON.stringify(deployments, null, 2));

  // ─── 3. index.js + index.d.ts ───────────────────────────────────────────
  const indexJs = `// Auto-generated by scripts/build-abi.mjs — do not edit by hand.
import AgentCertificate from './abi/AgentCertificate.json' with { type: 'json' };
import ZeroArenaINFT from './abi/ZeroArenaINFT.json' with { type: 'json' };
import ReencryptionOracle from './abi/ReencryptionOracle.json' with { type: 'json' };
import addresses from './addresses.json' with { type: 'json' };

export const abi = { AgentCertificate, ZeroArenaINFT, ReencryptionOracle };
export { addresses };
`;
  await writeFile(join(distDir, 'index.js'), indexJs);

  const indexDts = `import type { InterfaceAbi } from 'ethers';
export declare const abi: {
  AgentCertificate: InterfaceAbi;
  ZeroArenaINFT: InterfaceAbi;
  ReencryptionOracle: InterfaceAbi;
};
export interface DeploymentEntry {
  chainId: number;
  deployBlock: number | null;
  addresses: {
    AgentCertificate: string;
    ZeroArenaINFT: string;
    ReencryptionOracle: string;
  };
}
export declare const addresses: { galileo: DeploymentEntry };
`;
  await writeFile(join(distDir, 'index.d.ts'), indexDts);

  console.log(`✓ wrote @zero-arena/contracts artifacts to ${distDir}`);
  console.log(`  - ABIs:      ${CONTRACTS.length}`);
  console.log(`  - networks:  ${Object.keys(deployments).join(', ')}`);
}

main().catch((err) => {
  console.error('build-abi failed:', err.message);
  process.exit(1);
});
