#!/usr/bin/env node
// Build the @zero-arena/contracts npm package from the Foundry build
// artifacts. Reads ABIs out of `out/` and merges with the deployment JSONs.
//
// Output:
//   dist/abi/<Name>.json  (one per contract)
//   dist/addresses.json
//   dist/index.js
//   dist/index.d.ts

import { readFile, mkdir, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const CONTRACTS = [
  'AgentCertificate',
  'ZeroArenaINFT',
  'ReencryptionOracle',
  'LiveCertificate',
  'Season',
];

async function main() {
  const distDir = join(root, 'dist');
  if (existsSync(distDir)) await rm(distDir, { recursive: true, force: true });
  await mkdir(join(distDir, 'abi'), { recursive: true });

  for (const name of CONTRACTS) {
    const sourcePath = join(root, 'out', `${name}.sol`, `${name}.json`);
    if (!existsSync(sourcePath)) {
      throw new Error(`build-abi: ${sourcePath} not found. Run \`forge build\` first.`);
    }
    const raw = JSON.parse(await readFile(sourcePath, 'utf8'));
    if (!Array.isArray(raw.abi)) throw new Error(`build-abi: malformed artifact at ${sourcePath}`);
    await writeFile(join(distDir, 'abi', `${name}.json`), JSON.stringify(raw.abi, null, 2));
  }

  const addresses = { AgentCertificate: ZERO, ZeroArenaINFT: ZERO, ReencryptionOracle: ZERO, LiveCertificate: ZERO, Season: ZERO };
  let chainId = 16602;
  let deployBlock = null;

  const corePath = join(root, 'deployments', 'galileo-testnet.json');
  if (existsSync(corePath)) {
    const raw = JSON.parse(await readFile(corePath, 'utf8'));
    chainId = raw.chainId ?? chainId;
    deployBlock = raw.deployBlock ?? deployBlock;
    Object.assign(addresses, raw.addresses ?? {});
  }

  const paperPath = join(root, 'deployments', 'galileo-paper-engine.json');
  if (existsSync(paperPath)) {
    const raw = JSON.parse(await readFile(paperPath, 'utf8'));
    if (raw.paperEngine) {
      addresses.LiveCertificate = raw.paperEngine.LiveCertificate ?? addresses.LiveCertificate;
      addresses.Season = raw.paperEngine.Season ?? addresses.Season;
    }
  }

  const deployments = { galileo: { chainId, deployBlock, addresses } };
  await writeFile(join(distDir, 'addresses.json'), JSON.stringify(deployments, null, 2));

  const imports = CONTRACTS.map((n) => `import ${n} from './abi/${n}.json' with { type: 'json' };`).join('\n');
  const indexJs = `// Auto-generated by scripts/build-abi.mjs — do not edit by hand.
${imports}
import addresses from './addresses.json' with { type: 'json' };

export const abi = { ${CONTRACTS.join(', ')} };
export { addresses };
`;
  await writeFile(join(distDir, 'index.js'), indexJs);

  const indexDts = `import type { InterfaceAbi } from 'ethers';
export declare const abi: {
${CONTRACTS.map((n) => `  ${n}: InterfaceAbi;`).join('\n')}
};
export interface DeploymentEntry {
  chainId: number;
  deployBlock: number | null;
  addresses: {
${CONTRACTS.map((n) => `    ${n}: string;`).join('\n')}
  };
}
export declare const addresses: { galileo: DeploymentEntry };
`;
  await writeFile(join(distDir, 'index.d.ts'), indexDts);

  console.log(`✓ wrote @zero-arena/contracts artifacts to ${distDir}`);
  console.log(`  - ABIs:      ${CONTRACTS.length}`);
  console.log(`  - networks:  galileo (chain ${chainId})`);
}

const ZERO = '0x0000000000000000000000000000000000000000';

main().catch((err) => {
  console.error('build-abi failed:', err.message);
  process.exit(1);
});
