#!/usr/bin/env node
// Build the @zero-arena/contracts npm package from the Foundry build
// artifacts. Reads ABIs out of `out/` and merges with every chain's
// deployment JSON under `deployments/`.
//
// Output:
//   dist/abi/<Name>.json   (one per contract)
//   dist/addresses.json    { "<network>": { chainId, deployBlock, addresses } }
//   dist/index.js
//   dist/index.d.ts
//
// Network discovery: any file in `deployments/` whose name is either
//   <chainId>.json
//   <chainId>-paper-engine.json
//   galileo-testnet.json          (legacy alias)
//   galileo-paper-engine.json     (legacy alias)
// is parsed and the chainId is read from the JSON's `chainId` field.

import { readFile, readdir, mkdir, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const CONTRACTS = [
  'AgentCertificate',
  'ZeroArenaINFT',
  'ReencryptionOracle',
  'LiveCertificate',
  'Season',
];

const ZERO = '0x0000000000000000000000000000000000000000';

// chainId → display slug used as the key in addresses.json.
const NETWORK_SLUGS = {
  16602: 'galileo',
  16661: 'mainnet',
};

function slugForChainId(chainId) {
  return NETWORK_SLUGS[chainId] ?? `chain-${chainId}`;
}

async function main() {
  const distDir = join(root, 'dist');
  if (existsSync(distDir)) await rm(distDir, { recursive: true, force: true });
  await mkdir(join(distDir, 'abi'), { recursive: true });

  for (const name of CONTRACTS) {
    const sourcePath = join(root, 'out', `${name}.sol`, `${name}.json`);
    if (!existsSync(sourcePath)) {
      throw new Error(`build-abi: ${sourcePath} not found. Run \`forge build\` first.`);
    }
    const raw = JSON.parse(await readFile(sourcePath, 'utf8'));
    if (!Array.isArray(raw.abi)) throw new Error(`build-abi: malformed artifact at ${sourcePath}`);
    await writeFile(join(distDir, 'abi', `${name}.json`), JSON.stringify(raw.abi, null, 2));
  }

  // Per-chain accumulator keyed by chainId.
  const byChain = new Map();
  function entryFor(chainId) {
    if (!byChain.has(chainId)) {
      byChain.set(chainId, {
        chainId,
        deployBlock: null,
        addresses: {
          AgentCertificate: ZERO,
          ZeroArenaINFT: ZERO,
          ReencryptionOracle: ZERO,
          LiveCertificate: ZERO,
          Season: ZERO,
        },
      });
    }
    return byChain.get(chainId);
  }

  // Walk every JSON file in deployments/.
  const deploymentsDir = join(root, 'deployments');
  let files = [];
  try {
    files = await readdir(deploymentsDir);
  } catch {
    // No deployments yet — keep going so the package still builds.
  }

  for (const file of files) {
    if (!file.endsWith('.json')) continue;
    const raw = JSON.parse(await readFile(join(deploymentsDir, file), 'utf8'));
    const chainId = Number(raw.chainId);
    if (!Number.isFinite(chainId)) {
      console.warn(`build-abi: ${file} has no chainId — skipping`);
      continue;
    }
    const entry = entryFor(chainId);
    if (raw.addresses) {
      Object.assign(entry.addresses, raw.addresses);
    }
    if (raw.paperEngine) {
      entry.addresses.LiveCertificate = raw.paperEngine.LiveCertificate ?? entry.addresses.LiveCertificate;
      entry.addresses.Season = raw.paperEngine.Season ?? entry.addresses.Season;
    }
    if (raw.deployBlock != null) entry.deployBlock = raw.deployBlock;
  }

  const deployments = {};
  for (const [chainId, entry] of byChain.entries()) {
    deployments[slugForChainId(chainId)] = entry;
  }
  await writeFile(join(distDir, 'addresses.json'), JSON.stringify(deployments, null, 2));

  const imports = CONTRACTS.map((n) => `import ${n} from './abi/${n}.json' with { type: 'json' };`).join('\n');
  const indexJs = `// Auto-generated by scripts/build-abi.mjs — do not edit by hand.
${imports}
import addresses from './addresses.json' with { type: 'json' };

export const abi = { ${CONTRACTS.join(', ')} };
export { addresses };
`;
  await writeFile(join(distDir, 'index.js'), indexJs);

  const indexDts = `import type { InterfaceAbi } from 'ethers';
export declare const abi: {
${CONTRACTS.map((n) => `  ${n}: InterfaceAbi;`).join('\n')}
};
export interface DeploymentEntry {
  chainId: number;
  deployBlock: number | null;
  addresses: {
${CONTRACTS.map((n) => `    ${n}: string;`).join('\n')}
  };
}
export declare const addresses: Record<string, DeploymentEntry>;
`;
  await writeFile(join(distDir, 'index.d.ts'), indexDts);

  console.log(`✓ wrote @zero-arena/contracts artifacts to ${distDir}`);
  console.log(`  - ABIs:      ${CONTRACTS.length}`);
  if (byChain.size === 0) {
    console.log(`  - networks:  (none — run a deploy first)`);
  } else {
    for (const [chainId, entry] of byChain.entries()) {
      console.log(`  - network:   ${slugForChainId(chainId)} (chain ${chainId}, block ${entry.deployBlock ?? '?'})`);
    }
  }
}

main().catch((err) => {
  console.error('build-abi failed:', err.message);
  process.exit(1);
});
